/***************************************************************************
 *     Copyright (c) 1999-2006, Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Wed Jul 12 11:59:10 2006
 *                 MD5 Checksum         65dc148f276b8e1325bb5f85be0ccf82
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.006
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7401/rdb/c0/bchp_sun_top_ctrl.h $
 * 
 * Hydra_Software_Devel/1   7/14/06 1:14p jasonh
 * PR 22628: Initial version
 *
 ***************************************************************************/

#ifndef BCHP_SUN_TOP_CTRL_H__
#define BCHP_SUN_TOP_CTRL_H__

/***************************************************************************
 *SUN_TOP_CTRL - Top Control registers
 ***************************************************************************/
#define BCHP_SUN_TOP_CTRL_PROD_REVISION          0x00404000 /* Product Revision ID */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION           0x00404004 /* Sundry Revision ID */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL             0x00404008 /* Reset control */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG             0x0040400c /* Serial Slave Port configuration register */
#define BCHP_SUN_TOP_CTRL_SW_RESET               0x00404014 /* Software reset register */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL         0x00404018 /* Test port control */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE            0x0040401c /* Strapping values */
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH      0x00404020 /* Scratch register */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS            0x00404024 /* Bond option value register */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST        0x00404028 /* OTP option test register */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0            0x00404030 /* Semaphore channel 0 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1            0x00404034 /* Semaphore channel 1 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2            0x00404038 /* Semaphore channel 2 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3            0x0040403c /* Semaphore channel 3 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4            0x00404040 /* Semaphore channel 4 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5            0x00404044 /* Semaphore channel 5 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6            0x00404048 /* Semaphore channel 6 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7            0x0040404c /* Semaphore channel 7 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8            0x00404050 /* Semaphore channel 8 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9            0x00404054 /* Semaphore channel 9 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10           0x00404058 /* Semaphore channel 10 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11           0x0040405c /* Semaphore channel 11 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12           0x00404060 /* Semaphore channel 12 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13           0x00404064 /* Semaphore channel 13 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14           0x00404068 /* Semaphore channel 14 */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15           0x0040406c /* Semaphore channel 15 */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0         0x00404070 /* General watchdog timer 0 */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1         0x00404074 /* General watchdog timer 1 */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL              0x00404078 /* Sata control register */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL               0x0040407c /* DAA control register */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL          0x00404080 /* Simultaneous switching testmode control */
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL             0x00404084 /* Spare control bits reserved for future use */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN         0x00404088 /* EJTAG input bus enables */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL       0x0040408c /* EJTAG output select */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL      0x00404090 /* Block select for RO testmode */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0         0x00404094 /* Pin mux control register 0 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1         0x00404098 /* Pin mux control register 1 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2         0x0040409c /* Pin mux control register 2 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3         0x004040a0 /* Pin mux control register 3 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4         0x004040a4 /* Pin mux control register 4 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5         0x004040a8 /* Pin mux control register 5 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6         0x004040ac /* Pin mux control register 6 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7         0x004040b0 /* Pin mux control register 7 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8         0x004040b4 /* Pin mux control register 8 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9         0x004040b8 /* Pin mux control register 9 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10        0x004040bc /* Pin mux control register 10 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11        0x004040c0 /* Pin mux control register 11 */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12        0x004040c4 /* Pin mux control register 12 */

/***************************************************************************
 *PROD_REVISION - Product Revision ID
 ***************************************************************************/
/* SUN_TOP_CTRL :: PROD_REVISION :: product_revision [31:00] */
#define BCHP_SUN_TOP_CTRL_PROD_REVISION_product_revision_MASK      0xffffffff
#define BCHP_SUN_TOP_CTRL_PROD_REVISION_product_revision_SHIFT     0

/***************************************************************************
 *SUN_REVISION - Sundry Revision ID
 ***************************************************************************/
/* SUN_TOP_CTRL :: SUN_REVISION :: reserved0 [31:16] */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_reserved0_MASK              0xffff0000
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_reserved0_SHIFT             16

/* SUN_TOP_CTRL :: SUN_REVISION :: sundry_revision [15:00] */
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_sundry_revision_MASK        0x0000ffff
#define BCHP_SUN_TOP_CTRL_SUN_REVISION_sundry_revision_SHIFT       0

/***************************************************************************
 *RESET_CTRL - Reset control
 ***************************************************************************/
/* SUN_TOP_CTRL :: RESET_CTRL :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved0_MASK                0xffffff00
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved0_SHIFT               8

/* SUN_TOP_CTRL :: RESET_CTRL :: watchdog_reset_enable [07:07] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_MASK    0x00000080
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_watchdog_reset_enable_SHIFT   7

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_enable_lock [06:06] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_lock_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_lock_SHIFT 6

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_enable [05:05] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_enable_SHIFT 5

/* SUN_TOP_CTRL :: RESET_CTRL :: front_panel_reset_polarity [04:04] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_polarity_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_front_panel_reset_polarity_SHIFT 4

/* SUN_TOP_CTRL :: RESET_CTRL :: master_reset_en [03:03] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_master_reset_en_MASK          0x00000008
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_master_reset_en_SHIFT         3

/* SUN_TOP_CTRL :: RESET_CTRL :: reserved1 [02:02] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved1_MASK                0x00000004
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_reserved1_SHIFT               2

/* SUN_TOP_CTRL :: RESET_CTRL :: sc_insert_reset_en [01:00] */
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_sc_insert_reset_en_MASK       0x00000003
#define BCHP_SUN_TOP_CTRL_RESET_CTRL_sc_insert_reset_en_SHIFT      0

/***************************************************************************
 *SSP_CONFIG - Serial Slave Port configuration register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SSP_CONFIG :: reserved0 [31:11] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_reserved0_MASK                0xfffff800
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_reserved0_SHIFT               11

/* SUN_TOP_CTRL :: SSP_CONFIG :: serial_adr_cfg [10:07] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_serial_adr_cfg_MASK           0x00000780
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_serial_adr_cfg_SHIFT          7

/* SUN_TOP_CTRL :: SSP_CONFIG :: probe_mux_sel [06:03] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_probe_mux_sel_MASK            0x00000078
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_probe_mux_sel_SHIFT           3

/* SUN_TOP_CTRL :: SSP_CONFIG :: dly_disable [02:02] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_dly_disable_MASK              0x00000004
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_dly_disable_SHIFT             2

/* SUN_TOP_CTRL :: SSP_CONFIG :: spi_mode [01:01] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_spi_mode_MASK                 0x00000002
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_spi_mode_SHIFT                1

/* SUN_TOP_CTRL :: SSP_CONFIG :: ssp_module_enable [00:00] */
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_ssp_module_enable_MASK        0x00000001
#define BCHP_SUN_TOP_CTRL_SSP_CONFIG_ssp_module_enable_SHIFT       0

/***************************************************************************
 *SW_RESET - Software reset register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SW_RESET :: chip_master_reset [31:31] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_chip_master_reset_MASK          0x80000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_chip_master_reset_SHIFT         31

/* SUN_TOP_CTRL :: SW_RESET :: cpu_sw_reset_1shot [30:30] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_1shot_MASK         0x40000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_1shot_SHIFT        30

/* SUN_TOP_CTRL :: SW_RESET :: ext_sys_reset_1shot [29:29] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_1shot_MASK        0x20000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_1shot_SHIFT       29

/* SUN_TOP_CTRL :: SW_RESET :: reserved0 [28:26] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved0_MASK                  0x1c000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved0_SHIFT                 26

/* SUN_TOP_CTRL :: SW_RESET :: avd_sw_reset [25:25] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd_sw_reset_MASK               0x02000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_avd_sw_reset_SHIFT              25

/* SUN_TOP_CTRL :: SW_RESET :: aio_sw_reset [24:24] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_aio_sw_reset_MASK               0x01000000
#define BCHP_SUN_TOP_CTRL_SW_RESET_aio_sw_reset_SHIFT              24

/* SUN_TOP_CTRL :: SW_RESET :: rptd_sw_reset [23:23] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_rptd_sw_reset_MASK              0x00800000
#define BCHP_SUN_TOP_CTRL_SW_RESET_rptd_sw_reset_SHIFT             23

/* SUN_TOP_CTRL :: SW_RESET :: bvnm_sw_reset [22:22] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnm_sw_reset_MASK              0x00400000
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnm_sw_reset_SHIFT             22

/* SUN_TOP_CTRL :: SW_RESET :: ext_sys_reset_level [21:21] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_level_MASK        0x00200000
#define BCHP_SUN_TOP_CTRL_SW_RESET_ext_sys_reset_level_SHIFT       21

/* SUN_TOP_CTRL :: SW_RESET :: usb_sw_reset [20:20] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_usb_sw_reset_MASK               0x00100000
#define BCHP_SUN_TOP_CTRL_SW_RESET_usb_sw_reset_SHIFT              20

/* SUN_TOP_CTRL :: SW_RESET :: reserved1 [19:19] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved1_MASK                  0x00080000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved1_SHIFT                 19

/* SUN_TOP_CTRL :: SW_RESET :: sata_sw_reset [18:18] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_sata_sw_reset_MASK              0x00040000
#define BCHP_SUN_TOP_CTRL_SW_RESET_sata_sw_reset_SHIFT             18

/* SUN_TOP_CTRL :: SW_RESET :: reserved2 [17:17] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved2_MASK                  0x00020000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved2_SHIFT                 17

/* SUN_TOP_CTRL :: SW_RESET :: gfx_sw_reset [16:16] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_gfx_sw_reset_MASK               0x00010000
#define BCHP_SUN_TOP_CTRL_SW_RESET_gfx_sw_reset_SHIFT              16

/* SUN_TOP_CTRL :: SW_RESET :: reserved3 [15:14] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved3_MASK                  0x0000c000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved3_SHIFT                 14

/* SUN_TOP_CTRL :: SW_RESET :: xpt_sw_reset [13:13] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_xpt_sw_reset_MASK               0x00002000
#define BCHP_SUN_TOP_CTRL_SW_RESET_xpt_sw_reset_SHIFT              13

/* SUN_TOP_CTRL :: SW_RESET :: reserved4 [12:12] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved4_MASK                  0x00001000
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved4_SHIFT                 12

/* SUN_TOP_CTRL :: SW_RESET :: vec_sw_reset [11:11] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_vec_sw_reset_MASK               0x00000800
#define BCHP_SUN_TOP_CTRL_SW_RESET_vec_sw_reset_SHIFT              11

/* SUN_TOP_CTRL :: SW_RESET :: reserved5 [10:10] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved5_MASK                  0x00000400
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved5_SHIFT                 10

/* SUN_TOP_CTRL :: SW_RESET :: hdmi_sw_reset [09:09] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_hdmi_sw_reset_MASK              0x00000200
#define BCHP_SUN_TOP_CTRL_SW_RESET_hdmi_sw_reset_SHIFT             9

/* SUN_TOP_CTRL :: SW_RESET :: bvnb_sw_reset [08:08] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnb_sw_reset_MASK              0x00000100
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnb_sw_reset_SHIFT             8

/* SUN_TOP_CTRL :: SW_RESET :: bvnf_sw_reset [07:07] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnf_sw_reset_MASK              0x00000080
#define BCHP_SUN_TOP_CTRL_SW_RESET_bvnf_sw_reset_SHIFT             7

/* SUN_TOP_CTRL :: SW_RESET :: rfm_sw_reset [06:06] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_rfm_sw_reset_MASK               0x00000040
#define BCHP_SUN_TOP_CTRL_SW_RESET_rfm_sw_reset_SHIFT              6

/* SUN_TOP_CTRL :: SW_RESET :: reserved6 [05:05] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved6_MASK                  0x00000020
#define BCHP_SUN_TOP_CTRL_SW_RESET_reserved6_SHIFT                 5

/* SUN_TOP_CTRL :: SW_RESET :: enet_sw_reset [04:04] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_enet_sw_reset_MASK              0x00000010
#define BCHP_SUN_TOP_CTRL_SW_RESET_enet_sw_reset_SHIFT             4

/* SUN_TOP_CTRL :: SW_RESET :: cpu_sw_reset_level [03:03] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_level_MASK         0x00000008
#define BCHP_SUN_TOP_CTRL_SW_RESET_cpu_sw_reset_level_SHIFT        3

/* SUN_TOP_CTRL :: SW_RESET :: ebi_sw_reset [02:02] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_ebi_sw_reset_MASK               0x00000004
#define BCHP_SUN_TOP_CTRL_SW_RESET_ebi_sw_reset_SHIFT              2

/* SUN_TOP_CTRL :: SW_RESET :: pci_sw_reset [01:01] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_pci_sw_reset_MASK               0x00000002
#define BCHP_SUN_TOP_CTRL_SW_RESET_pci_sw_reset_SHIFT              1

/* SUN_TOP_CTRL :: SW_RESET :: sundry_sw_reset [00:00] */
#define BCHP_SUN_TOP_CTRL_SW_RESET_sundry_sw_reset_MASK            0x00000001
#define BCHP_SUN_TOP_CTRL_SW_RESET_sundry_sw_reset_SHIFT           0

/***************************************************************************
 *TEST_PORT_CTRL - Test port control
 ***************************************************************************/
/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: sundry_local_tp_out_sel [31:30] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_MASK 0xc0000000
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SHIFT 30
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SEMAPHORE 0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_SSP 1
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_RO_TEST 2
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_sundry_local_tp_out_sel_NOT_USED 3

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: reserved0 [29:07] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_reserved0_MASK            0x3fffff80
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_reserved0_SHIFT           7

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: tp_select [06:05] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_tp_select_MASK            0x00000060
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_tp_select_SHIFT           5

/* SUN_TOP_CTRL :: TEST_PORT_CTRL :: encoded_tp_enable [04:00] */
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_MASK    0x0000001f
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SHIFT   0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_ENET    0
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_CPU     1
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_RFM     2
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SATA    3
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNM    4
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNB    5
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_HDMI    6
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_VEC     8
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_GFX     14
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_HIF     15
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_USB     16
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_SUN     17
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BVNF    19
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_XPT     21
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_RPTD    22
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_AIO     23
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_AVD     24
#define BCHP_SUN_TOP_CTRL_TEST_PORT_CTRL_encoded_tp_enable_BSP     25

/***************************************************************************
 *STRAP_VALUE - Strapping values
 ***************************************************************************/
/* SUN_TOP_CTRL :: STRAP_VALUE :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved0_MASK               0x80000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved0_SHIFT              31

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_reset_outb_def_val [30:30] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_outb_def_val_MASK 0x40000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_outb_def_val_SHIFT 30

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_test_debug_en [29:28] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_test_debug_en_MASK     0x30000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_test_debug_en_SHIFT    28

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_nmi_polarity [27:27] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nmi_polarity_MASK      0x08000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nmi_polarity_SHIFT     27

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_sel_33_27_mhz_clock [26:26] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_sel_33_27_mhz_clock_MASK 0x04000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_sel_33_27_mhz_clock_SHIFT 26

/* SUN_TOP_CTRL :: STRAP_VALUE :: reserved1 [25:24] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved1_MASK               0x03000000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_reserved1_SHIFT              24

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_xtal_adj [23:20] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_xtal_adj_MASK          0x00f00000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_xtal_adj_SHIFT         20

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_rom_size [19:18] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_rom_size_MASK      0x000c0000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_rom_size_SHIFT     18

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_invert_addr [17:17] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_invert_addr_MASK   0x00020000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_invert_addr_SHIFT  17

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_boot_memory [16:16] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_boot_memory_MASK   0x00010000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_boot_memory_SHIFT  16

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ddr_configuration [15:13] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_configuration_MASK 0x0000e000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_configuration_SHIFT 13

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_system_big_endian [12:12] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_system_big_endian_MASK 0x00001000
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_system_big_endian_SHIFT 12

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ebi_cs_swap [11:11] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_cs_swap_MASK       0x00000800
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ebi_cs_swap_SHIFT      11

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_ddr_config3 [10:10] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_config3_MASK       0x00000400
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_ddr_config3_SHIFT      10

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_spi_slave_enable [09:09] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spi_slave_enable_MASK  0x00000200
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_spi_slave_enable_SHIFT 9

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin_size [08:07] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin_size_MASK   0x00000180
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin_size_SHIFT  7

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin2_en [06:06] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin2_en_MASK    0x00000040
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin2_en_SHIFT   6

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_memwin1_en [05:05] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin1_en_MASK    0x00000020
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_memwin1_en_SHIFT   5

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_pci_client [04:04] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_client_MASK        0x00000010
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_pci_client_SHIFT       4

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_nand_flash [03:03] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nand_flash_MASK        0x00000008
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_nand_flash_SHIFT       3

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_cpu_pll [02:01] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_cpu_pll_MASK           0x00000006
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_cpu_pll_SHIFT          1

/* SUN_TOP_CTRL :: STRAP_VALUE :: strap_reset_ext_mode [00:00] */
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_ext_mode_MASK    0x00000001
#define BCHP_SUN_TOP_CTRL_STRAP_VALUE_strap_reset_ext_mode_SHIFT   0

/***************************************************************************
 *UNCLEARED_SCRATCH - Scratch register
 ***************************************************************************/
/* SUN_TOP_CTRL :: UNCLEARED_SCRATCH :: uncleared_scratch [31:00] */
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH_uncleared_scratch_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_UNCLEARED_SCRATCH_uncleared_scratch_SHIFT 0

/***************************************************************************
 *BOND_STATUS - Bond option value register
 ***************************************************************************/
/* SUN_TOP_CTRL :: BOND_STATUS :: reserved0 [31:01] */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_reserved0_MASK               0xfffffffe
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_reserved0_SHIFT              1

/* SUN_TOP_CTRL :: BOND_STATUS :: bond_reserved [00:00] */
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_bond_reserved_MASK           0x00000001
#define BCHP_SUN_TOP_CTRL_BOND_STATUS_bond_reserved_SHIFT          0

/***************************************************************************
 *OTP_OPTION_TEST - OTP option test register
 ***************************************************************************/
/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: reserved0 [31:17] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_reserved0_MASK           0xfffe0000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_reserved0_SHIFT          17

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_spare [16:13] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_spare_MASK    0x0001e000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_spare_SHIFT   13

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_sata_disable [12:12] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_sata_disable_MASK 0x00001000
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_sata_disable_SHIFT 12

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_i2c [11:11] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_i2c_MASK   0x00000800
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_i2c_SHIFT  11

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_pci_ebi [10:10] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_pci_ebi_MASK 0x00000400
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_pci_ebi_SHIFT 10

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_en_testport [09:09] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_testport_MASK 0x00000200
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_en_testport_SHIFT 9

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_ebi_cs_swap_ovrd [08:08] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_ebi_cs_swap_ovrd_MASK 0x00000100
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_ebi_cs_swap_ovrd_SHIFT 8

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_hdcp_disable [07:07] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hdcp_disable_MASK 0x00000080
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hdcp_disable_SHIFT 7

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_macrovision_en [06:06] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_macrovision_en_MASK 0x00000040
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_macrovision_en_SHIFT 6

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_int_daa_enable [05:05] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_int_daa_enable_MASK 0x00000020
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_int_daa_enable_SHIFT 5

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_hd_display_enable [04:04] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hd_display_enable_MASK 0x00000010
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_hd_display_enable_SHIFT 4

/* SUN_TOP_CTRL :: OTP_OPTION_TEST :: otp_option_product_id [03:00] */
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_product_id_MASK 0x0000000f
#define BCHP_SUN_TOP_CTRL_OTP_OPTION_TEST_otp_option_product_id_SHIFT 0

/***************************************************************************
 *SEMAPHORE_0 - Semaphore channel 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_0 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_0 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_0_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_1 - Semaphore channel 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_1 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_1 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_1_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_2 - Semaphore channel 2
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_2 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_2 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_2_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_3 - Semaphore channel 3
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_3 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_3 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_3_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_4 - Semaphore channel 4
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_4 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_4 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_4_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_5 - Semaphore channel 5
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_5 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_5 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_5_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_6 - Semaphore channel 6
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_6 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_6 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_6_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_7 - Semaphore channel 7
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_7 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_7 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_7_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_8 - Semaphore channel 8
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_8 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_8 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_8_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_9 - Semaphore channel 9
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_9 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_reserved0_MASK               0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_reserved0_SHIFT              8

/* SUN_TOP_CTRL :: SEMAPHORE_9 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_semaphore_ctrl_MASK          0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_9_semaphore_ctrl_SHIFT         0

/***************************************************************************
 *SEMAPHORE_10 - Semaphore channel 10
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_10 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_10 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_10_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_11 - Semaphore channel 11
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_11 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_11 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_11_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_12 - Semaphore channel 12
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_12 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_12 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_12_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_13 - Semaphore channel 13
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_13 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_13 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_13_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_14 - Semaphore channel 14
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_14 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_14 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_14_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *SEMAPHORE_15 - Semaphore channel 15
 ***************************************************************************/
/* SUN_TOP_CTRL :: SEMAPHORE_15 :: reserved0 [31:08] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_reserved0_MASK              0xffffff00
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_reserved0_SHIFT             8

/* SUN_TOP_CTRL :: SEMAPHORE_15 :: semaphore_ctrl [07:00] */
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_semaphore_ctrl_MASK         0x000000ff
#define BCHP_SUN_TOP_CTRL_SEMAPHORE_15_semaphore_ctrl_SHIFT        0

/***************************************************************************
 *GEN_WATCHDOG_0 - General watchdog timer 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: GEN_WATCHDOG_0 :: watchdog_timeout_value [31:00] */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0_watchdog_timeout_value_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_0_watchdog_timeout_value_SHIFT 0

/***************************************************************************
 *GEN_WATCHDOG_1 - General watchdog timer 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: GEN_WATCHDOG_1 :: watchdog_timeout_value [31:00] */
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1_watchdog_timeout_value_MASK 0xffffffff
#define BCHP_SUN_TOP_CTRL_GEN_WATCHDOG_1_watchdog_timeout_value_SHIFT 0

/***************************************************************************
 *SATA_CTRL - Sata control register
 ***************************************************************************/
/* SUN_TOP_CTRL :: SATA_CTRL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_reserved0_MASK                 0xfffffff8
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_reserved0_SHIFT                3

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_sscen [02:02] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_sscen_MASK                0x00000004
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_sscen_SHIFT               2

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_ana_xtaliddq [01:01] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_xtaliddq_MASK         0x00000002
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_xtaliddq_SHIFT        1

/* SUN_TOP_CTRL :: SATA_CTRL :: sata_ana_pwrdn [00:00] */
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_pwrdn_MASK            0x00000001
#define BCHP_SUN_TOP_CTRL_SATA_CTRL_sata_ana_pwrdn_SHIFT           0

/***************************************************************************
 *DAA_CTRL - DAA control register
 ***************************************************************************/
/* SUN_TOP_CTRL :: DAA_CTRL :: reserved0 [31:02] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_reserved0_MASK                  0xfffffffc
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_reserved0_SHIFT                 2

/* SUN_TOP_CTRL :: DAA_CTRL :: daa_iddq [01:01] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_iddq_MASK                   0x00000002
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_iddq_SHIFT                  1

/* SUN_TOP_CTRL :: DAA_CTRL :: daa_bypass [00:00] */
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_bypass_MASK                 0x00000001
#define BCHP_SUN_TOP_CTRL_DAA_CTRL_daa_bypass_SHIFT                0

/***************************************************************************
 *SS_TMODE_CTRL - Simultaneous switching testmode control
 ***************************************************************************/
/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved0 [31:19] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved0_MASK             0xfff80000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved0_SHIFT            19

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bsp_ss_tmode_en [18:18] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bsp_ss_tmode_en_MASK       0x00040000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bsp_ss_tmode_en_SHIFT      18

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: avd_ss_tmode_en [17:17] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd_ss_tmode_en_MASK       0x00020000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_avd_ss_tmode_en_SHIFT      17

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: aio_ss_tmode_en [16:16] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_aio_ss_tmode_en_MASK       0x00010000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_aio_ss_tmode_en_SHIFT      16

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: rptd_ss_tmode_en [15:15] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_rptd_ss_tmode_en_MASK      0x00008000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_rptd_ss_tmode_en_SHIFT     15

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: sata_ss_tmode_en [14:14] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sata_ss_tmode_en_MASK      0x00004000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sata_ss_tmode_en_SHIFT     14

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: xpt_ss_tmode_en [13:13] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_xpt_ss_tmode_en_MASK       0x00002000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_xpt_ss_tmode_en_SHIFT      13

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: enet_ss_tmode_en [12:12] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_enet_ss_tmode_en_MASK      0x00001000
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_enet_ss_tmode_en_SHIFT     12

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved1 [11:08] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved1_MASK             0x00000f00
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved1_SHIFT            8

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: gfx_ss_tmode_en [07:07] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_gfx_ss_tmode_en_MASK       0x00000080
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_gfx_ss_tmode_en_SHIFT      7

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: sun_ss_tmode_en [06:06] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sun_ss_tmode_en_MASK       0x00000040
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_sun_ss_tmode_en_SHIFT      6

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: reserved2 [05:05] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved2_MASK             0x00000020
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_reserved2_SHIFT            5

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: usb_ss_tmode_en [04:04] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_usb_ss_tmode_en_MASK       0x00000010
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_usb_ss_tmode_en_SHIFT      4

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: hif_ss_tmode_en [03:03] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_hif_ss_tmode_en_MASK       0x00000008
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_hif_ss_tmode_en_SHIFT      3

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnm_ss_tmode_en [02:02] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnm_ss_tmode_en_MASK      0x00000004
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnm_ss_tmode_en_SHIFT     2

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnb_ss_tmode_en [01:01] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnb_ss_tmode_en_MASK      0x00000002
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnb_ss_tmode_en_SHIFT     1

/* SUN_TOP_CTRL :: SS_TMODE_CTRL :: bvnf_ss_tmode_en [00:00] */
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnf_ss_tmode_en_MASK      0x00000001
#define BCHP_SUN_TOP_CTRL_SS_TMODE_CTRL_bvnf_ss_tmode_en_SHIFT     0

/***************************************************************************
 *SPARE_CTRL - Spare control bits reserved for future use
 ***************************************************************************/
/* SUN_TOP_CTRL :: SPARE_CTRL :: spare_ctrl [31:00] */
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL_spare_ctrl_MASK               0xffffffff
#define BCHP_SUN_TOP_CTRL_SPARE_CTRL_spare_ctrl_SHIFT              0

/***************************************************************************
 *EJTAG_INPUT_EN - EJTAG input bus enables
 ***************************************************************************/
/* SUN_TOP_CTRL :: EJTAG_INPUT_EN :: reserved0 [31:05] */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_reserved0_MASK            0xffffffe0
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_reserved0_SHIFT           5

/* SUN_TOP_CTRL :: EJTAG_INPUT_EN :: ejtag_input_enable [04:00] */
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_MASK   0x0000001f
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_SHIFT  0
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_NOT_USED_CPU_ONE_HOT 1
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_MAIN_MIPS_CPU_ONE_HOT 2
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AUDIO_ZSP_CPU_ONE_HOT 4
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD_OL_CPU_ONE_HOT 8
#define BCHP_SUN_TOP_CTRL_EJTAG_INPUT_EN_ejtag_input_enable_AVD_IL_CPU_ONE_HOT 16

/***************************************************************************
 *EJTAG_OUTPUT_SEL - EJTAG output select
 ***************************************************************************/
/* SUN_TOP_CTRL :: EJTAG_OUTPUT_SEL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_reserved0_MASK          0xfffffff8
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_reserved0_SHIFT         3

/* SUN_TOP_CTRL :: EJTAG_OUTPUT_SEL :: ejtag_output_sel [02:00] */
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_MASK   0x00000007
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_SHIFT  0
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_NOT_USED_CPU 0
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_MAIN_MIPS_CPU 1
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AUDIO_ZSP_CPU 2
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD_OL_CPU 3
#define BCHP_SUN_TOP_CTRL_EJTAG_OUTPUT_SEL_ejtag_output_sel_AVD_IL_CPU 4

/***************************************************************************
 *RO_TEST_BLOCK_SEL - Block select for RO testmode
 ***************************************************************************/
/* SUN_TOP_CTRL :: RO_TEST_BLOCK_SEL :: reserved0 [31:03] */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_reserved0_MASK         0xfffffff8
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_reserved0_SHIFT        3

/* SUN_TOP_CTRL :: RO_TEST_BLOCK_SEL :: ro_test_block_select [02:00] */
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_MASK 0x00000007
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_SHIFT 0
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_NOT_USED_RO_TEST_ID 0
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_IOBUF_0_RO_TEST_ID 1
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_IOBUF_1_RO_TEST_ID 2
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_XPT_RO_TEST_ID 3
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_SUN_RO_TEST_ID 4
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_AVD_RO_TEST_ID 5
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_VEC_RO_TEST_ID 6
#define BCHP_SUN_TOP_CTRL_RO_TEST_BLOCK_SEL_ro_test_block_select_RPTD_RO_TEST_ID 7

/***************************************************************************
 *PIN_MUX_CTRL_0 - Pin mux control register 0
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: led_ld_1 [31:29] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_led_ld_1_MASK             0xe0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_led_ld_1_SHIFT            29

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: led_ld_0 [28:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_led_ld_0_MASK             0x18000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_led_ld_0_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_sync1 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync1_MASK            0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync1_SHIFT           24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_data1 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data1_MASK            0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data1_SHIFT           21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_clk1 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk1_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk1_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_sync0 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync0_MASK            0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_sync0_SHIFT           16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_data0 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data0_MASK            0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_data0_SHIFT           14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: rmx_clk0 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk0_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_rmx_clk0_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_sync2 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync2_MASK            0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync2_SHIFT           10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_sync1 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync1_MASK            0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync1_SHIFT           8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_sync0 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync0_MASK            0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_sync0_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_data2 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data2_MASK            0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data2_SHIFT           4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_data1 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data1_MASK            0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data1_SHIFT           2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_0 :: pkt_data0 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data0_MASK            0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_0_pkt_data0_SHIFT           0

/***************************************************************************
 *PIN_MUX_CTRL_1 - Pin mux control register 1
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: vi0_656_1 [31:29] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_vi0_656_1_MASK            0xe0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_vi0_656_1_SHIFT           29

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: vi0_656_0 [28:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_vi0_656_0_MASK            0x1c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_vi0_656_0_SHIFT           26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ls_4 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_4_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_4_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ls_3 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_3_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_3_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ls_2 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_2_MASK             0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_2_SHIFT            20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ls_1 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_1_MASK             0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_1_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ls_0 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_0_MASK             0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ls_0_SHIFT            16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_7 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_7_MASK             0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_7_SHIFT            14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_6 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_6_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_6_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_5 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_5_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_5_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_4 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_4_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_4_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_3 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_3_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_3_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_1 :: led_ld_2 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_2_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_1_led_ld_2_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_2 - Pin mux control register 2
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_5 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_5_MASK             0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_5_SHIFT            30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_4 [29:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_4_MASK             0x30000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_4_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_3 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_3_MASK             0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_3_SHIFT            26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_2 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_2_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_2_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_1 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_1_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_1_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vo_656_0 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_0_MASK             0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vo_656_0_SHIFT            20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_clk [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_clk_MASK          0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_clk_SHIFT         18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_7 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_7_MASK            0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_7_SHIFT           15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_6 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_6_MASK            0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_6_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_5 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_5_MASK            0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_5_SHIFT           9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_4 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_4_MASK            0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_4_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_3 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_3_MASK            0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_3_SHIFT           3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_2 :: vi0_656_2 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_2_MASK            0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_2_vi0_656_2_SHIFT           0

/***************************************************************************
 *PIN_MUX_CTRL_3 - Pin mux control register 3
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_reserved0_MASK            0x80000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_reserved0_SHIFT           31

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad08 [30:29] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad08_MASK             0x60000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad08_SHIFT            29

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad07 [28:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad07_MASK             0x18000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad07_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad06 [26:25] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad06_MASK             0x06000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad06_SHIFT            25

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad05 [24:23] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad05_MASK             0x01800000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad05_SHIFT            23

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad04 [22:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad04_MASK             0x00600000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad04_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad03 [20:19] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad03_MASK             0x00180000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad03_SHIFT            19

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad02 [18:17] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad02_MASK             0x00060000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad02_SHIFT            17

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad01 [16:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad01_MASK             0x00018000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad01_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: pci_ad00 [14:13] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad00_MASK             0x00006000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_pci_ad00_SHIFT            13

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: i2s_lr [12:11] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_lr_MASK               0x00001800
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_lr_SHIFT              11

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: i2s_data [10:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_data_MASK             0x00000700
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_data_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: i2s_clk [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_clk_MASK              0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_i2s_clk_SHIFT             6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: vo_656_clk [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_clk_MASK           0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_clk_SHIFT          4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: vo_656_7 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_7_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_7_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_3 :: vo_656_6 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_6_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_3_vo_656_6_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_4 - Pin mux control register 4
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad24 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad24_MASK             0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad24_SHIFT            30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad23 [29:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad23_MASK             0x30000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad23_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad22 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad22_MASK             0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad22_SHIFT            26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad21 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad21_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad21_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad20 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad20_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad20_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad19 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad19_MASK             0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad19_SHIFT            20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad18 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad18_MASK             0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad18_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad17 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad17_MASK             0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad17_SHIFT            16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad16 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad16_MASK             0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad16_SHIFT            14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad15 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad15_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad15_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad14 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad14_MASK             0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad14_SHIFT            10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad13 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad13_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad13_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad12 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad12_MASK             0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad12_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad11 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad11_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad11_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad10 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad10_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad10_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_4 :: pci_ad09 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad09_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_4_pci_ad09_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_5 - Pin mux control register 5
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: reserved0 [31:31] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_reserved0_MASK            0x80000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_reserved0_SHIFT           31

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: ir_in1 [30:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_in1_MASK               0x70000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_in1_SHIFT              28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: ir_in0 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_in0_MASK               0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_in0_SHIFT              26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: ir_out [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_out_MASK               0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_ir_out_SHIFT              24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: daa_aout [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_daa_aout_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_daa_aout_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_cbe03 [21:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe03_MASK            0x00300000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe03_SHIFT           20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_cbe02 [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe02_MASK            0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe02_SHIFT           18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_cbe01 [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe01_MASK            0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe01_SHIFT           16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_cbe00 [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe00_MASK            0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_cbe00_SHIFT           14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad31 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad31_MASK             0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad31_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad30 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad30_MASK             0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad30_SHIFT            10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad29 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad29_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad29_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad28 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad28_MASK             0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad28_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad27 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad27_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad27_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad26 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad26_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad26_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_5 :: pci_ad25 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad25_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_5_pci_ad25_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_6 - Pin mux control register 6
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_05 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_05_MASK              0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_05_SHIFT             27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_04 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_04_MASK              0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_04_SHIFT             24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_03 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_03_MASK              0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_03_SHIFT             21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_02 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_02_MASK              0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_02_SHIFT             18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_01 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_01_MASK              0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_01_SHIFT             15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: gpio_00 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_00_MASK              0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_gpio_00_SHIFT             12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_ext_clk [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_ext_clk_MASK           0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_ext_clk_SHIFT          10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_vcc_0 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_vcc_0_MASK             0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_vcc_0_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_pres_0 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_pres_0_MASK            0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_pres_0_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_rst_0 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_rst_0_MASK             0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_rst_0_SHIFT            4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_clk_0 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_clk_0_MASK             0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_clk_0_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_6 :: sc_io_0 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_io_0_MASK              0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_6_sc_io_0_SHIFT             0

/***************************************************************************
 *PIN_MUX_CTRL_7 - Pin mux control register 7
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_15 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_15_MASK              0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_15_SHIFT             27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_14 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_14_MASK              0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_14_SHIFT             24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_13 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_13_MASK              0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_13_SHIFT             21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_12 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_12_MASK              0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_12_SHIFT             18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_11 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_11_MASK              0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_11_SHIFT             15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_10 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_10_MASK              0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_10_SHIFT             12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_09 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_09_MASK              0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_09_SHIFT             9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_08 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_08_MASK              0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_08_SHIFT             6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_07 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_07_MASK              0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_07_SHIFT             3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_7 :: gpio_06 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_06_MASK              0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_7_gpio_06_SHIFT             0

/***************************************************************************
 *PIN_MUX_CTRL_8 - Pin mux control register 8
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_25 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_25_MASK              0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_25_SHIFT             27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_24 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_24_MASK              0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_24_SHIFT             24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_23 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_23_MASK              0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_23_SHIFT             21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_22 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_22_MASK              0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_22_SHIFT             18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_21 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_21_MASK              0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_21_SHIFT             15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_20 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_20_MASK              0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_20_SHIFT             12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_19 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_19_MASK              0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_19_SHIFT             9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_18 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_18_MASK              0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_18_SHIFT             6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_17 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_17_MASK              0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_17_SHIFT             3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_8 :: gpio_16 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_16_MASK              0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_8_gpio_16_SHIFT             0

/***************************************************************************
 *PIN_MUX_CTRL_9 - Pin mux control register 9
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: reserved0 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_reserved0_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_reserved0_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_35 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_35_MASK              0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_35_SHIFT             27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_34 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_34_MASK              0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_34_SHIFT             24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_33 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_33_MASK              0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_33_SHIFT             21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_32 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_32_MASK              0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_32_SHIFT             18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_31 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_31_MASK              0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_31_SHIFT             15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_30 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_30_MASK              0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_30_SHIFT             12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_29 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_29_MASK              0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_29_SHIFT             9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_28 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_28_MASK              0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_28_SHIFT             6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_27 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_27_MASK              0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_27_SHIFT             3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_9 :: gpio_26 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_26_MASK              0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_9_gpio_26_SHIFT             0

/***************************************************************************
 *PIN_MUX_CTRL_10 - Pin mux control register 10
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_46 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_46_MASK             0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_46_SHIFT            30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_45 [29:27] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_45_MASK             0x38000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_45_SHIFT            27

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_44 [26:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_44_MASK             0x07000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_44_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_43 [23:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_43_MASK             0x00e00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_43_SHIFT            21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_42 [20:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_42_MASK             0x001c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_42_SHIFT            18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_41 [17:15] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_41_MASK             0x00038000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_41_SHIFT            15

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_40 [14:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_40_MASK             0x00007000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_40_SHIFT            12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_39 [11:09] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_39_MASK             0x00000e00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_39_SHIFT            9

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_38 [08:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_38_MASK             0x000001c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_38_SHIFT            6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_37 [05:03] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_37_MASK             0x00000038
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_37_SHIFT            3

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_10 :: gpio_36 [02:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_36_MASK             0x00000007
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_10_gpio_36_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_11 - Pin mux control register 11
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: sgpio_00 [31:30] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_00_MASK            0xc0000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_sgpio_00_SHIFT           30

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_58 [29:28] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_58_MASK             0x30000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_58_SHIFT            28

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_57 [27:26] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_57_MASK             0x0c000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_57_SHIFT            26

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_56 [25:24] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_56_MASK             0x03000000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_56_SHIFT            24

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_55 [23:22] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_55_MASK             0x00c00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_55_SHIFT            22

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_54 [21:19] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_54_MASK             0x00380000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_54_SHIFT            19

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_53 [18:17] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_53_MASK             0x00060000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_53_SHIFT            17

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_52 [16:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_52_MASK             0x0001c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_52_SHIFT            14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_51 [13:11] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_51_MASK             0x00003800
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_51_SHIFT            11

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_50 [10:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_50_MASK             0x00000700
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_50_SHIFT            8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_49 [07:05] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_49_MASK             0x000000e0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_49_SHIFT            5

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_48 [04:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_48_MASK             0x0000001c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_48_SHIFT            2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_11 :: gpio_47 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_47_MASK             0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_11_gpio_47_SHIFT            0

/***************************************************************************
 *PIN_MUX_CTRL_12 - Pin mux control register 12
 ***************************************************************************/
/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: reserved0 [31:21] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_reserved0_MASK           0xffe00000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_reserved0_SHIFT          21

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: byp_sys9_clk [20:20] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_byp_sys9_clk_MASK        0x00100000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_byp_sys9_clk_SHIFT       20

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: ejtag_tdi [19:18] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tdi_MASK           0x000c0000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tdi_SHIFT          18

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: ejtag_tck [17:16] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tck_MASK           0x00030000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tck_SHIFT          16

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: ejtag_tms [15:14] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tms_MASK           0x0000c000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_ejtag_tms_SHIFT          14

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_07 [13:12] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_07_MASK            0x00003000
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_07_SHIFT           12

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_06 [11:10] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_06_MASK            0x00000c00
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_06_SHIFT           10

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_05 [09:08] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_05_MASK            0x00000300
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_05_SHIFT           8

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_04 [07:06] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_04_MASK            0x000000c0
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_04_SHIFT           6

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_03 [05:04] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_03_MASK            0x00000030
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_03_SHIFT           4

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_02 [03:02] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_02_MASK            0x0000000c
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_02_SHIFT           2

/* SUN_TOP_CTRL :: PIN_MUX_CTRL_12 :: sgpio_01 [01:00] */
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_01_MASK            0x00000003
#define BCHP_SUN_TOP_CTRL_PIN_MUX_CTRL_12_sgpio_01_SHIFT           0

#endif /* #ifndef BCHP_SUN_TOP_CTRL_H__ */

/* End of File */
